FORMAT: 1A

# Warcard
Rest API для связи с игровым сервером

# Group Games
Вызов API связанных с игровым процесом

## Games Collection [/games]
### Получить список доступных игры [GET]
+ Request (application/json)

        {"type":"1", "map":["1,2"]}

+ Response 200 (application/json)

        [{
          "id": 1, "map": "1", "type":"1"
        }, {
          "id": 2, "map": "1", "type":"1"
        }]
        
+ Response 204 (application/json)

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Game [/game/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
